"""init tables for trivia

Revision ID: 3965843b8926
Revises: 
Create Date: 2020-02-25 13:23:33.074632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3965843b8926'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'type',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('questions', 'answer',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('questions', 'difficulty',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('questions', 'question',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questions', 'question',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('questions', 'difficulty',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('questions', 'answer',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('categories', 'type',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
